name: controller_builder
description: Widget for abstracting initializing and disposing TextEditingController, ChangeNotifiers, etc.
version: 1.0.0+1
repository: https://github.com/Luckey-Elijah/controller_builder
issues: https://github.com/Luckey-Elijah/controller_builder/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
