name: Controller Builder

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/controller_builder_verify_and_test.yaml'
      - '**'

  push:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/**'
      - '**'


jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: .
      min_coverage: 100
      flutter_channel: stable
      flutter_version: 3.0.4